# Generated by Django 5.2.8 on 2026-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_populate_temple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
