# Generated by Django 5.2.8 on 2026-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_out_of_station_profile_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='temple_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='residency',
            field=models.CharField(default='Main Residency', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
