# Generated by Django 5.2.8 on 2026-05-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_temple_name_profile_residency_and_more'),
        ('temple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='temple.temple'),
        ),
    ]
