# Generated by Django 6.0.5 on 2026-05-18 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SadhanaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadhana_date', models.DateField()),
                ('folk_residency', models.CharField(max_length=50)),
                ('mangal_aarti', models.CharField(max_length=10)),
                ('group_japa', models.CharField(max_length=10)),
                ('sb_class', models.CharField(max_length=10)),
                ('rounds_chanted', models.IntegerField()),
                ('sp_reading', models.CharField(max_length=10)),
                ('assigned_service', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadhana_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
