# Generated by Django 5.2.8 on 2026-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadhana', '0002_alter_sadhanaentry_id_sadhanalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadhanaentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sadhanalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
