# Generated by Django 5.2.8 on 2026-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sevaduty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
