# Generated by Django 5.2.8 on 2026-05-19 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0004_masterservice_remove_service_name_service_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sevaduty',
            name='service_instance',
        ),
        migrations.RemoveField(
            model_name='sevaduty',
            name='user',
        ),
        migrations.CreateModel(
            name='WeeklyServiceAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('residency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('active', models.BooleanField(default=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySeva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('seva_date', models.DateField()),
                ('start_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('completed', models.BooleanField(default=False)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sevas', to=settings.AUTH_USER_MODEL)),
                ('weekly_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sevas', to='seva.weeklyserviceassignment')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
