# Generated by Django 5.2.8 on 2026-05-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_seva_duty'),
        ('seva', '0005_remove_sevaduty_service_instance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SevaDuty',
        ),
    ]
