# Generated by Django 5.2.8 on 2026-05-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0006_delete_sevaduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyseva',
            name='reminder_10_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='reminder_start_sent',
            field=models.BooleanField(default=False),
        ),
    ]
