# Generated by Django 5.2.8 on 2026-05-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seva', '0007_dailyseva_reminder_10_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyseva',
            name='assignment_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='last_reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='overdue_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='reminder_30_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='service_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyseva',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
