# Generated by Django 5.2.8 on 2026-05-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
        ('seva', '0005_remove_sevaduty_service_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seva_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seva.dailyseva'),
        ),
    ]
